//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acuminator.Runner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acuminator.Runner.NetFramework.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code source to use for Acuminator validation is not found at {0}.
        /// </summary>
        internal static string CodeSourceNotFoundError {
            get {
                return ResourceManager.GetString("CodeSourceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code source is not specified.
        /// </summary>
        internal static string CodeSourceNotSpecifiedError {
            get {
                return ResourceManager.GetString("CodeSourceNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain compilation with analyzers.
        /// </summary>
        internal static string FailedToObtainCompilationWithAnalyzersError {
            get {
                return ResourceManager.GetString("FailedToObtainCompilationWithAnalyzersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported code source {0}. You can specify only C# projects (*.csproj) and solutions (*.sln) as code sources..
        /// </summary>
        internal static string NotSupportedCodeSourceType {
            get {
                return ResourceManager.GetString("NotSupportedCodeSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported output format &quot;{0}&quot;. You can specify only &quot;{1}&quot; and &quot;{2}&quot; values as output formats..
        /// </summary>
        internal static string NotSupportedOutputFormat {
            get {
                return ResourceManager.GetString("NotSupportedOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Acuminator code analysis runner, the CLI tool that runs Acuminator diagnostics!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
