//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acuminator.Runner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acuminator.Runner.NetFramework.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &quot;{0}&quot; passed Acuminator validation successfully.
        /// </summary>
        internal static string AcuminatorValidationPassedMessage {
            get {
                return ResourceManager.GetString("AcuminatorValidationPassedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuminator version &quot;{Version}&quot; is used for the analysis..
        /// </summary>
        internal static string AcuminatorVersionInfo {
            get {
                return ResourceManager.GetString("AcuminatorVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened during the Acuminator analysis of &quot;{CodeSource}&quot;..
        /// </summary>
        internal static string AnalysisOfCodeSourceRuntimeError {
            get {
                return ResourceManager.GetString("AnalysisOfCodeSourceRuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Acuminator validation of the &quot;{CodeSource}&quot;. Project &quot;{ProjectName}&quot; validation result: {Result}..
        /// </summary>
        internal static string CancelledCodeSourceValidationInfo {
            get {
                return ResourceManager.GetString("CancelledCodeSourceValidationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation is finished. &quot;{CodeSource}&quot; failed the validation..
        /// </summary>
        internal static string CodeSourceFailedValidationMessage {
            get {
                return ResourceManager.GetString("CodeSourceFailedValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code source to use for Acuminator validation is not found at {0}.
        /// </summary>
        internal static string CodeSourceNotFoundError {
            get {
                return ResourceManager.GetString("CodeSourceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code source is not specified.
        /// </summary>
        internal static string CodeSourceNotSpecifiedError {
            get {
                return ResourceManager.GetString("CodeSourceNotSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Acuminator validation of &quot;{CodeSource}&quot; was cancelled..
        /// </summary>
        internal static string CodeSourceValidationWasCancelled {
            get {
                return ResourceManager.GetString("CodeSourceValidationWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinct Diagnostics.
        /// </summary>
        internal static string DistinctDiagnosticsReportTitlePart {
            get {
                return ResourceManager.GetString("DistinctDiagnosticsReportTitlePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the collection of Acuminator analyzers.
        /// </summary>
        internal static string ErrorDuringAcuminatorAnalyzersCollection {
            get {
                return ResourceManager.GetString("ErrorDuringAcuminatorAnalyzersCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Count.
        /// </summary>
        internal static string ErrorsCountReportTitlePart {
            get {
                return ResourceManager.GetString("ErrorsCountReportTitlePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Acuminator global suppression mechanism for the code source &quot;{CodeSource}&quot;..
        /// </summary>
        internal static string FailedToInitializeAcuminatorGlobalSuppressionMechanismError {
            get {
                return ResourceManager.GetString("FailedToInitializeAcuminatorGlobalSuppressionMechanismError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Acuminator analyzers. The analysis of the code source &quot;{CodeSource}&quot; cannot be performed.
        /// </summary>
        internal static string FailedToLoadAcuminatorAnalyzersError {
            get {
                return ResourceManager.GetString("FailedToLoadAcuminatorAnalyzersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load solution from the code source &quot;{CodeSource}&quot;..
        /// </summary>
        internal static string FailedToLoadSolutionFromCodeSourceError {
            get {
                return ResourceManager.GetString("FailedToLoadSolutionFromCodeSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain Acuminator version. The analysis will be performed without Acuminator version information..
        /// </summary>
        internal static string FailedToObtainAcuminatorVersionWarning {
            get {
                return ResourceManager.GetString("FailedToObtainAcuminatorVersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain compilation with analyzers.
        /// </summary>
        internal static string FailedToObtainCompilationWithAnalyzersError {
            get {
                return ResourceManager.GetString("FailedToObtainCompilationWithAnalyzersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain Roslyn compilation data for the project with name &quot;{ProjectName}&quot; and path &quot;{ProjectPath}&quot;..
        /// </summary>
        internal static string FailedToObtainRoslynCompilationDataForTheProjectError {
            get {
                return ResourceManager.GetString("FailedToObtainRoslynCompilationDataForTheProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Acuminator validation of the project &quot;{ProjectName}&quot;. Project validation result: {Result}..
        /// </summary>
        internal static string FinishedAcuminatorValidationOfTheProjectInfo {
            get {
                return ResourceManager.GetString("FinishedAcuminatorValidationOfTheProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Errors.
        /// </summary>
        internal static string FoundErrorsReportSubtitle {
            get {
                return ResourceManager.GetString("FoundErrorsReportSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Acuminator analyzers..
        /// </summary>
        internal static string InitializeAcuminatorAnalyzersStatusMessage {
            get {
                return ResourceManager.GetString("InitializeAcuminatorAnalyzersStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of loaded projects: {ProjectsCount}..
        /// </summary>
        internal static string LoadedProjectsCount_Information {
            get {
                return ResourceManager.GetString("LoadedProjectsCount_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found MSBuild instance with name &quot;{VisualStudioName}&quot;, version &quot;{VisualStudioVersion}&quot;..
        /// </summary>
        internal static string MSBuild_VisualStudioNameAndVersion_Info {
            get {
                return ResourceManager.GetString("MSBuild_VisualStudioNameAndVersion_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during registration of MSBuild instance..
        /// </summary>
        internal static string MSBuildInstanceRegistrationError {
            get {
                return ResourceManager.GetString("MSBuildInstanceRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBuildPath: &quot;{MSBuildPath}&quot;..
        /// </summary>
        internal static string MSBuildPath_Info {
            get {
                return ResourceManager.GetString("MSBuildPath_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the registration of MSBuild instance. Failed to register MSBuild using a provided path &quot;{MSBuildPath}&quot;..
        /// </summary>
        internal static string MSBuildRegistrationAtProvidedPathFailedError {
            get {
                return ResourceManager.GetString("MSBuildRegistrationAtProvidedPathFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file.
        /// </summary>
        internal static string NoFilePlaceholder {
            get {
                return ResourceManager.GetString("NoFilePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No installed MSBuild version was found on the machine..
        /// </summary>
        internal static string NoInstalledMSBuildFoundError {
            get {
                return ResourceManager.GetString("NoInstalledMSBuildFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project in the provided &quot;{CodeSource}&quot; references Acumatica Platform.
        /// </summary>
        internal static string NoProjectInCodeSourceReferencesAcumaticaPlatformError {
            get {
                return ResourceManager.GetString("NoProjectInCodeSourceReferencesAcumaticaPlatformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported code source {0}. You can specify only C# projects (*.csproj) and solutions (*.sln) as code sources..
        /// </summary>
        internal static string NotSupportedCodeSourceType {
            get {
                return ResourceManager.GetString("NotSupportedCodeSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported output format &quot;{0}&quot;. You can specify only &quot;{1}&quot; and &quot;{2}&quot; values as output formats..
        /// </summary>
        internal static string NotSupportedOutputFormat {
            get {
                return ResourceManager.GetString("NotSupportedOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained Roslyn compilation data for the project &quot;{ProjectName}&quot; successfully..
        /// </summary>
        internal static string ObtainedRoslynCompilationDataForTheProjectDebug {
            get {
                return ResourceManager.GetString("ObtainedRoslynCompilationDataForTheProjectDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining Roslyn compilation data for the project &quot;{ProjectName}&quot;..
        /// </summary>
        internal static string ObtainingRoslynCompilationDataForTheProjectDebug {
            get {
                return ResourceManager.GetString("ObtainingRoslynCompilationDataForTheProjectDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project {ProjectName} does not reference Acumatica Platform. Validation can not be performed.
        /// </summary>
        internal static string ProjectDoesNotReferenceAcumaticaPlatformValidationError {
            get {
                return ResourceManager.GetString("ProjectDoesNotReferenceAcumaticaPlatformValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering MSBuild instance at the provided path &quot;{MSBuildPath}&quot;..
        /// </summary>
        internal static string RegisteringMSBuildAtTheProvidedPathStatusMessage {
            get {
                return ResourceManager.GetString("RegisteringMSBuildAtTheProvidedPathStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A runtime error was encountered during the validation..
        /// </summary>
        internal static string RuntimeErrorHappenedDuringValidationMessage {
            get {
                return ResourceManager.GetString("RuntimeErrorHappenedDuringValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for MSBuild instances installed on the current machine..
        /// </summary>
        internal static string SearchingForMSBuildInstancesStatusMessage {
            get {
                return ResourceManager.GetString("SearchingForMSBuildInstancesStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start analyzing the code source &quot;{CodeSource}&quot;..
        /// </summary>
        internal static string StartAnalyzingTheCodeSourceStatusMessage {
            get {
                return ResourceManager.GetString("StartAnalyzingTheCodeSourceStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Acuminator validation of the project &quot;{ProjectName}&quot;..
        /// </summary>
        internal static string StartedAcuminatorValidationOfTheProjectInfo {
            get {
                return ResourceManager.GetString("StartedAcuminatorValidationOfTheProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start loading the code source &quot;{CodeSource}&quot;..
        /// </summary>
        internal static string StartLoadingTheCodeSourceAtPathStatusMessage {
            get {
                return ResourceManager.GetString("StartLoadingTheCodeSourceAtPathStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start validating the solution..
        /// </summary>
        internal static string StartValidatingSolutionStatusMessage {
            get {
                return ResourceManager.GetString("StartValidatingSolutionStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully finished validating the solution..
        /// </summary>
        internal static string SuccessfullyFinishedSolutionValidationStatusMessage {
            get {
                return ResourceManager.GetString("SuccessfullyFinishedSolutionValidationStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded the code source &quot;{CodeSource}&quot;..
        /// </summary>
        internal static string SuccessfullyLoadedCodeSourceAtPathStatusMessage {
            get {
                return ResourceManager.GetString("SuccessfullyLoadedCodeSourceAtPathStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered MSBuild instance at the provided path &quot;{MSBuildPath}&quot;..
        /// </summary>
        internal static string SuccessfullyRegisteredMSBuildAtProvidedPathStatusMessage {
            get {
                return ResourceManager.GetString("SuccessfullyRegisteredMSBuildAtProvidedPathStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Errors Count.
        /// </summary>
        internal static string TotalErrorsCountReportTitlePart {
            get {
                return ResourceManager.GetString("TotalErrorsCountReportTitlePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on attempt to unregister MSBuild..
        /// </summary>
        internal static string UnregisterMSBuildInstanceError {
            get {
                return ResourceManager.GetString("UnregisterMSBuildInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation passed successfully!.
        /// </summary>
        internal static string ValidationPassedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ValidationPassedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation was successfully cancelled..
        /// </summary>
        internal static string ValidationWasSuccessfullyCancelledDebugInfo {
            get {
                return ResourceManager.GetString("ValidationWasSuccessfullyCancelledDebugInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Acuminator code analysis runner, the CLI tool that runs Acuminator diagnostics!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
